/**
 * Cross-validation: Node TS crypto MUST match relay/crypto.py byte-for-byte.
 * Vectors generated by /tmp/gen_vectors.py (fixed deterministic keys).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  KeyPair,
  computeSharedSecret,
  deriveEncKey,
  encrypt,
  decrypt,
  channelIdFromPairingCode,
  makeNonce,
  hkdfSha256,
} from "../src/crypto.ts";

const V = {
  alicePriv: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
  alicePub: "8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f",
  bobPriv: "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
  bobPub: "358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254",
  code: "K7M2P9QX",
  channel: "2af47aa2f8eeaa9c",
  sharedAb: "a8e5e88e608f7e5262b5025efb95e8faa162296ed1a406a2acce7ef38d4009ca",
  keyAppToAgent: "f18e78c20b1dea86e9e98e351a546a208b904a524f02f378171b356f7e8e8fd6",
  keyAgentToApp: "9a02e75a1af9174004ba21928e135681b1b754a6eccf0177d88320cdc6195253",
  plaintext: '{"jsonrpc":"2.0","id":7,"method":"session.list"}',
  seq: 3,
  // Generated by relay/crypto.py (gen_vectors.py, fixed keys) — the TS side
  // MUST reproduce this wire payload byte-for-byte.
  wireB64:
    "AAAAAyr0eqL47qqcTEzQlKKXxmHBohii106/7LTTqKIuJFdi2XBHhCNLTjtsYH9nstbM6EDatx7O89TDlDizXEdsRTwKGY3rxWOEVw==",
};

test("channel id from pairing code", () => {
  assert.equal(channelIdFromPairingCode(V.code), V.channel);
  // 16-char codes (current pairing rule) derive the same way — the crypto
  // layer is length-agnostic (SHA-256 over the code); the length rule lives
  // in the protocol/UI validation layers.
  const sixteen = channelIdFromPairingCode("K7M2P9QX3F5B8TZ2");
  assert.equal(sixteen.length, 16);
  assert.match(sixteen, /^[0-9a-f]{16}$/);
});

test("X25519 public derivation", async () => {
  const alice = await KeyPair.fromPrivateBytes(Buffer.from(V.alicePriv, "hex"));
  assert.equal(Buffer.from(alice.publicBytes).toString("hex"), V.alicePub);
  const bob = await KeyPair.fromPrivateBytes(Buffer.from(V.bobPriv, "hex"));
  assert.equal(Buffer.from(bob.publicBytes).toString("hex"), V.bobPub);
});

test("PSK-blended ECDH shared secret matches python", async () => {
  const shared = await computeSharedSecret(
    Buffer.from(V.alicePriv, "hex"),
    Buffer.from(V.bobPub, "hex"),
    Buffer.from(V.code),
  );
  assert.equal(Buffer.from(shared).toString("hex"), V.sharedAb);
});

test("HKDF-SHA256 (zero salt) matches python", () => {
  const out = hkdfSha256(Buffer.from("abc"), 32, Buffer.alloc(0), Buffer.from("info"));
  assert.equal(out.length, 32);
  // Cross-checked against python _hkdf_sha256(b"abc",32,b"",b"info")
  assert.equal(
    out.toString("hex"),
    "fbbdb0ec7d9189cd8b7f47b4a54557ea496080065283a64627f9c8770e3c005f",
  );
});

test("encrypt/decrypt roundtrip and wire format matches python", async () => {
  // Derive the SAME key python used (app_to_agent).
  const shared = await computeSharedSecret(
    Buffer.from(V.alicePriv, "hex"),
    Buffer.from(Buffer.from(V.bobPub, "hex")),
    Buffer.from(V.code),
  );
  const key = deriveEncKey(shared, "app_to_agent");
  const wire = encrypt(Buffer.from(V.plaintext, "utf-8"), key, V.seq, V.channel);
  // Nonce prefix must be seq(4B BE) + channel(8B)
  const raw = Buffer.from(wire, "base64");
  assert.equal(raw.readUInt32BE(0), V.seq);
  assert.equal(raw.subarray(4, 12).toString("hex"), V.channel);
  // Byte-for-byte against Python's crypto.py output.
  assert.equal(wire, V.wireB64, "wire must match crypto.py byte-for-byte");
  // Roundtrip
  const back = decrypt(wire, key).toString("utf-8");
  assert.equal(back, V.plaintext);
});

test("makeNonce format", () => {
  const n = makeNonce(3, V.channel);
  // 4B seq + 8B channel (16 hex chars → 8 bytes)
  assert.equal(n.toString("hex"), "00000003" + V.channel);
});